#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 182218-web-01 4.175.58.102:80 check\n\tserver 182218-web-02 34.227.93.191:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
